function transformarBairrosCrasEmObjeto(
  bairrosCras: Bairro[]
): Record<string, string[]> {
  return bairrosCras.reduce((acc, { cras, bairro }) => {
    acc[cras] = bairro;
    return acc;
  }, {} as Record<string, string[]>);
}

export interface Bairro {
  cras: string;
  bairro: Array<string>;
}

export const BairroCras: Bairro[] = [
  {
    cras: 'CHATUBA',
    bairro: [
      'CARVAO',
      'CHATUBA',
      'FAZENDINHA',
      'JOAO MARIA',
      'PARQUE ALPHAVILLE',
      'PARQUE ALPHAVILLE II',
      'PARQUE AURORA',
      'PARQUE CARLOS DE LACERDA',
      'PARQUE DR BEDA',
      'PARQUE IPS',
      'PARQUE JOAO SEIXAS ',
      'PARQUE ROSARIO ',
      'PARQUE RUI BARBOSA ',
      'PARQUE SAO BENEDITO ',
      'PARQUE SAO LINO ',
      'CANTAGALO ',
      'CAPAO',
      'PARQUE FAZENDA GRANDE',
    ],
  },

  {
    cras: 'CODIN',
    bairro: [
      'CODIN',
      'JARDIM BOA VISTA',
      'LAGOA DAS PEDRAS',
      'NOVO ELDORADO',
      'PARQUE ELDORADO',
      'PARQUE JARDIM AEROPORTO',
      'PARQUE JARDIM CEASA',
      'PARQUE SANTOS DUMONT',
      'PARQUE SAO SILVESTRE',
      'TERRA PROMETIDA',
      'VILA INDUSTRIAL',
      'KM 5 A 8',
    ],
  },

  {
    cras: 'CUSTODOPOLIS',
    bairro: [
      'PARQUE BANDEIRANTES',
      'PARQUE BARAO DO RIO BRANCO ',
      'PARQUE BONSUCESSO ',
      'PARQUE CUSTODOPOLIS ',
      'PARQUE NOVA CAMPOS ',
      'PARQUE NOVO MUNDO ',
      'PARQUE SANTA CLARA ',
      'PARQUE SANTA ROSA ',
      'PARQUE SAO DOMINGOS ',
      'RESIDENCIAL PLANICIE',
      'COND SANTA ROSA ',
      'COND SANTA ROSA 2 ',
      'COND DOS NOGUEIRAS',
    ],
  },
  {
    cras: 'JD CARIOCA',
    bairro: [
      'PARQUE ALVORADA',
      'JARDIM CARIOCA ',
      'PARQUE NITEROI ',
      'PARQUE PRAZERES ',
      'PARQUE PRESIDENTE VARGAS',
      'PARQUE RESIDENCIAL DA LAPA II',
      'PARQUE SANTO ANTONIO ',
      'PARQUE VICENTE GONÇALVES DIAS',
      'ZUZA MOTA',
      'USINA SAO JOAO',
    ],
  },
  {
    cras: 'PARQUE GUARUS',
    bairro: [
      'INVASAO CIDADE LUZ',
      'BOA VISTA ',
      'PARQUE ALDEIA ',
      'PARQUE ALDEIA I ',
      'PARQUE ALDEIA II',
      'PARQUE CIDADE LUZ',
      'PARQUE FUNDAO',
      'PARQUE GUARUS',
      'PARQUE JD GUARUS',
      'PARQUE LEBRET',
      'PARQUE SANTA HELENA ',
      'PARQUE SAO MATHEUS ',
      'PARQUE SAO JOSE',
      'PARQUE VERA CRUZ',
      'SAPUCAIA ',
      'TRES VENDAS',
    ],
  },
  {
    cras: 'TRAVESSAO',
    bairro: [
      'BALANCA RANGEL',
      'BREJO GRANDE',
      'CAMPELO',
      'CANAA',
      'CAXETA',
      'GUANDU',
      'MATUTU',
      'MUNDEOS',
      'NOVA CONAA',
      'RIBEIRO DO AMARO',
      'SANTANA',
      'TRAVESSAO',
      'SAO DIOGO',
      'ESCOVA URUBU',
      'KM 9 A 16',
    ],
  },
  {
    cras: 'GOYTACAZES',
    bairro: [
      'ALTO DA AREIA',
      'ALTO DO ELISEU',
      'BALTAZAR',
      'BARRA DO JACARE',
      'BEIRA DO FAZ',
      'BEIRA DO TAI',
      'BUGALHO',
      'CABOIO',
      'CAMPOS LIMPO',
      'CANAL DAS FLEXAS',
      'CANTO DO ENGENHO',
      'CANTO DO RIO TOCOS',
      'CARIOCA DE TOCOS',
      'CAXIAS DE TOCOS',
      'CAZUMBA',
      'COQUEIRO DE TOCOS',
      'CORRENTEZA',
      'CUPIM DE POCO GORDO',
      'DONANA',
      'ESPINHO',
      'GAIVOTAS',
      'GOIABA',
      'GOITACAZES',
      'JARDIM PARAISO DE TOCOS',
      'JARDIM PRIMAVERA',
      'LINHA DO LIMAO',
      'MARCELO',
      'MINEIROS',
      'MONTENEGRO',
      'MUTEMA',
      'NOVA GOYTACAZES',
      'PARQUE SAO SILVANO',
      'PARQUE REAL',
      'PARQUE SAO SILVANO',
      'PARQUE SARAIVA',
      'PARQUE TRANSMISSOR',
      'PAUS AMARELOS',
      'POCO GORDO',
      'PONTA GROSSA',
      'PONTO DE COQUEIROS',
      'PONTO DO CARMO',
      'SABAO',
      'SATURNINO BRAGA',
      'SAO MARTINHO',
      'SAO SEBASTIAO',
      'TOCAIA',
      'TOCOS VALA DO MATO',
      'VILA REAL',
      'VILA ROMANA',
    ],
  },

  {
    cras: 'FAROL',
    bairro: [
      'BABOSA',
      'BAIXA GRANDE',
      'BOA VISTA',
      'CAMPO DE AREIA',
      'CIPRIAO',
      'CORREGO FUNDO',
      'FAROL DE SAO THOME',
      'FAROLZINHO',
      'LAGAMAR',
      'LARGO DO GARCIA',
      'MARRECAS',
      'MULACO',
      'MUSSUREPE',
      'PARQUE MOSTEIRO DE SAO BENTO',
      'PARQUE NAUTICO',
      'PITANGUEIRA',
      'QUIXABA',
      'RADIO VELHO',
      'RETIRO',
      'SANTO AMARO DE CAMPOS',
      'TERMINAL PESQUEIRO',
      'VEIGA',
      'VIEGAS',
      'VILA DO SOL',
      'VILA DOS PESCADORES',
      'XEXE',
    ],
  },

  {
    cras: 'JOCKEY',
    bairro: [
      'JOCKEY CLUB',
      'NOVO JOCKEY',
      'JOCKEY I',
      'JOCKEY II',
      'BENTA PEREIRA',
      'VISTA ALEGRE',
      'MORADO DO ORIENTE',
      'CAMBAIBA',
      'CAMPO NOVO',
      'MARTINS LAGE',
      'VENDA NOVA',
    ],
  },
  {
    cras: 'MATADOURO',
    bairro: [
      'CHACARA JOAO FERREIRA',
      'HORTO',
      'JARDIM FLAMBOYANT I',
      'JARDIM FLAMBOYANT II',
      'LAPA',
      'MATADOURO',
      'PARQUE CALIFORNIA',
      'PARQUE OLIVEIRA BOTELHO',
      'PARQUE RIACHUELO',
      'PARQUE SALO BRAND',
      'PARQUE TURF CLUB',
      'CENTRO (OU ESPLANADA)',
      'TIRA GOSTO',
    ],
  },

  {
    cras: 'PENHA',
    bairro: [
      'COND CIDADE VERDE',
      'ESTANCIA DA PENHA',
      'FAZENDINHA',
      'PARQUE ANGELICA',
      'PENHA',
      'PARQUE BELA VISTA',
      'PARQUE IMPERIAL',
      'PARQUE JOSE DO PATROCINIO',
      'PARQUE TROPICAL',
      'PARQUE CONJ. SANTA MARIA',
      'PARQUE DO PRADO',
      'PARQUE JD DAS ACACIAS',
      'PARQUE RES SANTO ANTONIO',
      'PARQUE RES PORTO SEGURO',
      'PARQUE TARCISIO MIRANDA',
      'PARQUE VARANDA DO VISCONDE',
      'PARQUE VILA MENEZES',
      'PARQUE VILA VERDE',
      'RES. VIVENDAS DA PENHA I',
      'RES. VIVENDAS DA PENHA II',
      'SOLAR DA PENHA',
      'USINA SANTO ANTONIO',
      'VILA MANHAES',
      'VIVENDAS DO COQUEIROS',
      'VIVENDAS DOS COQUEIROS II',
    ],
  },

  {
    cras: 'MORRO DO COCO',
    bairro: [
      'AREIA BRANCA',
      'CHAVE DO PARAISO',
      'CONSELHEIRO JOSINO',
      'ESPIRITO SANTINHO',
      'MATA DA CRUZ',
      'MORRO DO COCO',
      'MURUNDU',
      'PALMARES',
      'SANTA BARBARA',
      'SANTA MARIA',
      'SANTO EDUARDO',
      'SAO LUIS DE MUTUCA',
      'SAO ROQUE',
      'SESMARIA',
      'VILA NOVA',
      'DIVISA',
    ],
  },

  {
    cras: 'ESPLANADA',
    bairro: [
      'CAJU',
      'ITERERE',
      'MORANGABA',
      'PARQUE CORRIENTES',
      'PARQUE DOM BOSCO',
      'PARQUE DOS RODOVIARIOS',
      'PARQUE ESPLANADA',
      'JARDIM MARIA DE QUEIROZ',
      'PARQUE JULIAO NOGUEIRA',
      'PARQUE LEOPOLDINA',
      'NOSSA SRA DO ROSARIO',
      'NOVA BRASILIA',
      'PECUARIA',
      'PARQUE SANTO AMARO',
      'PARQUE SAO CAETANO',
      'PARQUE SUMARE',
      'PARQUE TAMANDARE',
      'SANTA CRUZ',
      'CENTRO (OU MATADOURO',
    ],
  },

  {
    cras: 'URURAI',
    bairro: [
      'ACAMP SEM TERRA ESTRADA LEITE',
      'ASSENT ALELUIA',
      'ASEENT ANTONIO FARIAS',
      'ASSENT BATATAL',
      'ASSENT CAMBUCA',
      'ASSENT TERRA CONQUISTADA',
      'CEREJEIRA',
      'CONCEICAO DO IMBE',
      'DORES DE MACABU',
      'GURIRI',
      'IBITIOCA',
      'IMBE',
      'LAGOA DE CIMA',
      'MACACO',
      'MATO ESCURO',
      'MORRO GRANDE',
      'PEDRA NEGRA',
      'PERNAMBUCA',
      'PLANICIE',
      'PONTA DA LAMA',
      'QUILOMBO',
      'SENTINELA DO IMBBE',
      'SERRINHA',
      'TAPERA',
      'URURAI',
      'VIANA',
    ],
  },
];

const bairrosPorCras = transformarBairrosCrasEmObjeto(BairroCras);
console.log(bairrosPorCras); // Exibe o objeto no console
